name       : pbr
version    : 5.8.1
release    : 15
source     :
    - https://pypi.python.org/packages/source/p/pbr/pbr-5.8.1.tar.gz : 66bc5a34912f408bb3925bf21231cb6f59206267b7f63f3503ef865c1a292e25
license    : Apache-2.0
component  : programming.python
summary    : Python Build Reasonableness
description: |
    PBR is a library to automatically do a bunch of standard things you want in your setup.py without you having to repeat them every time. It will set versions, process requirements files and generate AUTHORS and ChangeLog file all from git information.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
