name       : pbr
version    : 1.10.0
release    : 4
source     :
    - https://pypi.python.org/packages/c3/2c/63275fab26a0fd8cadafca71a3623e4d0f0ee8ed7124a5bb128853d178a7/pbr-1.10.0.tar.gz : 186428c270309e6fdfe2d5ab0949ab21ae5f7dea831eab96701b86bd666af39c
license    : Apache-2.0
component  : programming.python
summary    : Python Build Reasonableness
description: |
    PBR is a library to automatically do a bunch of standard
    things you want in your setup.py without you having to repeat
    them every time. It will set versions, process requirements
    files and generate AUTHORS and ChangeLog file all from git
    information.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |-
    %python_install
    %python3_install
