name       : pbr
version    : 0.11.1
release    : 1
source     :
    - https://pypi.python.org/packages/source/p/pbr/pbr-0.11.1.tar.gz : 701ab2922c29ca6004e3a4aab968728f33224968de9b51e432be2ee3340c2309
license    : Apache-2.0
summary    : Python Build Reasonableness
description: |
    PBR is a library to automatically do a bunch of standard
    things you want in your setup.py without you having to repeat
    them every time. It will set versions, process requirements
    files and generate AUTHORS and ChangeLog file all from git
    information.
builddeps  :
    - pkgconfig(python)
    - pip
setup      : |
    # Get rid of ugly build-time deps that require network:
    sed -i "s/, 'sphinx\.ext\.intersphinx'//" doc/source/conf.py
    #python setup.py configure
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
