name       : pbr
version    : 5.7.0
release    : 12
source     :
    - https://pypi.python.org/packages/source/p/pbr/pbr-5.7.0.tar.gz : 4651ca1445e80f2781827305de3d76b3ce53195f2227762684eb08f17bc473b7
license    : Apache-2.0
component  : programming.python
summary    : Python Build Reasonableness
description: |
    PBR is a library to automatically do a bunch of standard things you want in your setup.py without you having to repeat them every time. It will set versions, process requirements files and generate AUTHORS and ChangeLog file all from git information.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
