name       : pbr
version    : 5.8.0
release    : 13
source     :
    - https://pypi.python.org/packages/source/p/pbr/pbr-5.8.0.tar.gz : 672d8ebee84921862110f23fcec2acea191ef58543d34dfe9ef3d9f13c31cddf
license    : Apache-2.0
component  : programming.python
summary    : Python Build Reasonableness
description: |
    PBR is a library to automatically do a bunch of standard things you want in your setup.py without you having to repeat them every time. It will set versions, process requirements files and generate AUTHORS and ChangeLog file all from git information.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
